In [ ]:
# Проценко Іван Андрійович Варіант - 15

In [241]:
# 1. Створіть одновимірний масив (вектор) з простими числами, не перевищуючи 70, та виведіть його значення.

In [242]:
import numpy as np
import random

In [243]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True

print(np.array([x for x in range(2, 71) if is_prime(x)]))

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67]


In [244]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями квадратів перших натуральних чисел.

In [245]:
numbers = np.arange(1, 10)
squares = numbers ** 2

print(squares.reshape(3, 3))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [246]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами від -10 до 10 та знайдіть максимальний елемент

In [247]:
numbers = np.random.randint(-10, 11, size=25)
matrix = numbers.reshape(5, 5)

print("Матриця:\n", matrix)

max_value = np.max(matrix)
print("Максимальний елемент:", max_value)

Матриця:
 [[-3  1  1 -2 -8]
 [-2 10 10  6 -9]
 [-3 -3 -4  8 10]
 [-9 -5  2 -9  9]
 [ 0 -5 -2  4 -3]]
Максимальний елемент: 10


In [248]:
# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-рядок, що містить максимальні елементи в кожному стовпці.

In [249]:
matrix = np.random.rand(4, 4)
print("Матриця:\n", matrix)
max_in_columns = np.max(matrix, axis=0)
print("Вектор максимальних елементів по стовпцях:\n", max_in_columns)


Матриця:
 [[0.56371857 0.84739182 0.44050353 0.29059457]
 [0.26220697 0.22013078 0.22211325 0.32138492]
 [0.0917007  0.34485859 0.46085095 0.24487547]
 [0.21360936 0.94631255 0.02350636 0.34008142]]
Вектор максимальних елементів по стовпцях:
 [0.56371857 0.94631255 0.46085095 0.34008142]


In [250]:
# 5. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами в діапазоні від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [251]:
a = np.random.randint(-10, 11, size=7)
b = np.random.randint(-10, 11, size=7)

print("Масив a:", a)
print("Масив b:", b)

add = a + b
sub = a - b
mul = a * b
print("Додавання:", add)
print("Віднімання:", sub)
print("Множення:", mul)


Масив a: [-2 -1  5  3  3 -8  1]
Масив b: [ 4  5 -9 -5  0  1  8]
Додавання: [ 2  4 -4 -2  3 -7  9]
Віднімання: [-6 -6 14  8  3 -9 -7]
Множення: [ -8  -5 -45 -15   0  -8   8]


In [252]:
# 6.  Створіть дві матриці 4x4, заповніть їх довільними цілими числами від -10 до 10 та знайдіть їх добуток.


In [253]:
A = np.random.randint(-10, 11, size=(4, 4))
B = np.random.randint(-10, 11, size=(4, 4))

print("Матриця A:\n", A)
print("Матриця B:\n", B)

product = np.dot(A, B)
print("Добуток A * B:\n", product)

Матриця A:
 [[-8 -3 -6 -1]
 [-3  4 10  9]
 [10 -4 -8 -2]
 [ 5  0  6  4]]
Матриця B:
 [[ 9 -7  8 -8]
 [ 0 -3  3  8]
 [-2  0 -8 -2]
 [10  9 -1  1]]
Добуток A * B:
 [[ -70   56  -24   51]
 [  43   90 -101   45]
 [  86  -76  134  -98]
 [  73    1  -12  -48]]


In [254]:
# 7. Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами від 1 до 3 та перемножте їх між собою.

In [255]:
C = np.random.randint(1, 4, size=(4, 2))
D = np.random.randint(1, 4, size=(2, 2))

print("Матриця C:\n", C)
print("Матриця D:\n", D)

result = np.dot(C, D)
print("Добуток C * D:\n", result)

Матриця C:
 [[2 2]
 [2 3]
 [1 2]
 [3 1]]
Матриця D:
 [[2 3]
 [2 1]]
Добуток C * D:
 [[ 8  8]
 [10  9]
 [ 6  5]
 [ 8 10]]


In [256]:
# 8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю.

In [257]:
M = np.random.randint(1, 8, size=(2, 2))
print("Матриця M:\n", M)
print("Обернена матриця:\n", np.linalg.inv(M))

Матриця M:
 [[2 7]
 [6 6]]
Обернена матриця:
 [[-0.2         0.23333333]
 [ 0.2        -0.06666667]]


In [258]:
# 9. Створіть матрицю розміром 3x5, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.

In [259]:
M = np.random.randint(0, 2, size=(3, 5))
print("Матриця M:\n", M)
print("Транспонована матриця:\n", M.T)

Матриця M:
 [[1 1 0 0 0]
 [0 0 1 0 0]
 [0 1 0 1 0]]
Транспонована матриця:
 [[1 0 0]
 [1 0 1]
 [0 1 0]
 [0 0 1]
 [0 0 0]]


In [260]:
# 10. Створіть матрицю 3x4 з випадковими дійсними числами від 0 до 1 та вектор 4x1 з випадковими числами від 0 до 1

In [261]:
M = np.random.rand(3, 4)
v = np.random.rand(4, 1)
print("Матриця M:\n", M)
print("Вектор v:\n", v)

Матриця M:
 [[0.5840291  0.00929744 0.74691221 0.96117396]
 [0.22736103 0.2168847  0.95105393 0.6008866 ]
 [0.53558228 0.48721155 0.42859097 0.50315338]]
Вектор v:
 [[0.5908033 ]
 [0.25211309]
 [0.28469243]
 [0.91324654]]


In [262]:
# 11. Створіть матрицю 2x3 та вектор 3x1 з випадковими дійсними числами від 0 до 1 і знайдіть суму елементів матриці, менших за відповідний елемент вектора

In [263]:
M = np.random.rand(2, 3)
v = np.random.rand(3, 1)
print("Матриця M:\n", M)
print("Вектор v:\n", v)

sum_elements = np.sum(M < v.T)
print("Сума елементів менших за відповідні елементи вектора:", sum_elements)

Матриця M:
 [[0.00665016 0.88574681 0.35153862]
 [0.87860093 0.0517959  0.57515861]]
Вектор v:
 [[0.78074358]
 [0.76265715]
 [0.5094736 ]]
Сума елементів менших за відповідні елементи вектора: 3


In [264]:
# 12. Створіть дві матриці 8x8 з випадковими цілими числами від 1 до 10 та знайдіть їхню суму

In [265]:
A = np.random.randint(1, 11, size=(8, 8))
B = np.random.randint(1, 11, size=(8, 8))
print("A:\n", A)
print("B:\n", B)
print("Сума матриць:\n", A + B)

A:
 [[ 7  3  3  7  7  3  9  6]
 [ 4  3  2  1  1  5  2  8]
 [ 1  2  1  6 10  9  7  5]
 [ 9  4  2  6  2  8  6  7]
 [ 5  1  1  6  8  5  8  2]
 [ 1  2  1  1  1 10  3  3]
 [ 9  2  3 10  3  8  1  8]
 [ 3  8  1  5  9  9  8  3]]
B:
 [[ 2  6  6  1  8 10  4  9]
 [ 1  8  4  2  1  6  2  4]
 [ 3  4  4  5  4  1  8  9]
 [ 6  1  3  7  4  7  7  4]
 [ 8  7  8  4  1  7  1  5]
 [ 3  2  9  4  9  2  5  8]
 [ 6  3  8  8  5 10  8  5]
 [ 6  5  8 10  4  9  9  7]]
Сума матриць:
 [[ 9  9  9  8 15 13 13 15]
 [ 5 11  6  3  2 11  4 12]
 [ 4  6  5 11 14 10 15 14]
 [15  5  5 13  6 15 13 11]
 [13  8  9 10  9 12  9  7]
 [ 4  4 10  5 10 12  8 11]
 [15  5 11 18  8 18  9 13]
 [ 9 13  9 15 13 18 17 10]]


In [266]:
# 13. Створіть дві матриці 3x3 з випадковими дійсними числами від -1 до 1 та знайдіть добуток їх елементів

In [267]:
A = np.random.uniform(-1, 1, size=(3, 3))
B = np.random.uniform(-1, 1, size=(3, 3))
print("A:\n", A)
print("B:\n", B)
print("Добуток елементів:\n", A * B)

A:
 [[ 0.89361427  0.76378103  0.90098008]
 [ 0.53046133  0.23948063 -0.49560268]
 [-0.94073911 -0.01286068  0.02412678]]
B:
 [[ 0.07266433  0.61259135  0.90704911]
 [-0.76577087  0.20853408  0.62751534]
 [-0.3695755  -0.98829344 -0.07353395]]
Добуток елементів:
 [[ 0.06493388  0.46788565  0.81723318]
 [-0.40621183  0.04993987 -0.31099829]
 [ 0.34767413  0.01271013 -0.00177414]]


In [268]:
# 14. Створіть матрицю 3x3 з випадковими дійсними числами від -5 до 5 та знайдіть добуток елементів, більших за середнє

In [269]:
M = np.random.uniform(-5, 5, size=(3, 3))
mean_val = np.mean(M)
print("Матриця M:\n", M)
print("Середнє значення:", mean_val)
product = np.prod(M[M > mean_val])
print("Добуток елементів більших за середнє:", product)

Матриця M:
 [[ 1.25704237 -1.71875993 -1.27907825]
 [ 1.25549529  1.5687326  -0.01182937]
 [ 0.55439112 -0.68851654 -2.52695528]]
Середнє значення: -0.1766086668106556
Добуток елементів більших за середнє: -0.016236475675805287


In [270]:
# 15. Створіть матрицю 3x3 з випадковими дійсними числами від -0.5 до 0.5 та знайдіть вектор-стовпчик з найбільшими за модулем цілими значеннями в кожному рядку

In [271]:
M = np.random.uniform(-0.5, 0.5, size=(3, 3))
max_abs_int = np.array([int(np.round(np.max(np.abs(M[i])))) for i in range(M.shape[0])]).reshape(-1, 1)
print("Матриця M:\n", M)
print("Вектор-стовпчик найбільших за модулем цілих чисел по рядках:\n", max_abs_int)

Матриця M:
 [[ 0.19580168  0.05130416  0.11287425]
 [ 0.07887418  0.27471481 -0.07435805]
 [-0.07090345 -0.00433532  0.09180091]]
Вектор-стовпчик найбільших за модулем цілих чисел по рядках:
 [[0]
 [0]
 [0]]


In [ ]:
# Ці завдання навчали створювати та обробляти одновимірні і двовимірні масиви з випадковими числами, виконувати поелементні та матричні операції, а також працювати з умовами для вибору елементів. Використання NumPy дозволяє легко знаходити суму, добуток, максимум, транспонувати та обертати матриці. Це формує базові навички роботи з масивами та лінійною алгеброю в Python.
